# fly.toml app configuration file generated for felipefarias-phonebook-frontend on 2024-01-03T15:33:51-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "felipefarias-phonebook-frontend"
primary_region = "scl"

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
